-- *** Lubaduste valdkonnad ***
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (12,3,'Terve Tartu');
INSERT INTO lubadus_valdkond(valdkondid,pealkiri) VALUES (2,'Parima elukeskkonnaga linn');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (13,4,'Kodanike linn');
INSERT INTO lubadus_valdkond(valdkondid,pealkiri) VALUES (1,'Eesti Reformierakonna, Eesti Keskerakonna ja Sotsiaaldemokraatliku Erakonna koalitsioonilepe Tartu linna juhtimiseks aastatel 2013-2017');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (11,3,'Eesti hariduskeskus');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (14,4,'Vaba ettevõtluskeskkond');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (8,2,'Mugavad ühendused Tartus ja Tartuga');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (6,1,'Ühised väärtused');
INSERT INTO lubadus_valdkond(valdkondid,pealkiri) VALUES (3,'Parim linn arenemiseks');
INSERT INTO lubadus_valdkond(valdkondid,pealkiri) VALUES (4,'Targalt juhitud linn');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (10,2,'Sotsiaalne turvatunne');
INSERT INTO lubadus_valdkond(valdkondid,pealkiri) VALUES (5,'Tööjaotus linna juhtimisel ja esindamisel');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (7,2,'Kultuurilinn');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (9,2,'Roheline ja targalt planeeritud linn');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (16,5,'Linnavalitsus');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (17,5,'Linnavolikogu');
INSERT INTO lubadus_valdkond(valdkondid,ylemvaldkondid,pealkiri) VALUES (15,4,'Tartu koostöövõrgustikes ja linna ruumiline areng');
-- *** Lubadused ise ***
-- 1 Eesti Reformierakonna, Eesti Keskerakonna ja Sotsiaaldemokraatliku Erakonna koalitsioonilepe Tartu linna juhtimiseks aastatel 2013-2017
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (1, 'Käesolev lepe tugineb Eesti Reformierakonna, Eesti Keskerakonna ja Sotsiaaldemokraatliku Erakonna 20. oktoobril 2013. a toimunud Tartu Linnavolikogu valimisteks koostatud programmidele, Tartu linna arengukavadele ja arengustrateegiale, osaliste maailmavaatelisusele ja ka teiste 2013. aastal Tartu Linnavolikogusse valituks osutunud erakondade ja valimisliitude programmidele.', 1,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (2, 'Koalitsioonileppe eesmärgiks on välja tuua ühiselt kokkulepitud prioriteedid ja tegevused järgmisel neljal aastal, mis aitavad kaasa Tartu linna pikaajaliste strateegiliste eesmärkide täitmisele.', 1,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (3, 'Tartu visioon aastaks 2030 on olla tegusate, loovate ja õnnelike inimeste linn. Tartu on Eesti vaimupealinn ja traditsioonidega ülikoolilinn: nooruselinn, kus loovus ja avatud mõtlemine toetavad arendustegevust, ettevõtlust ja innovatsiooni. Tartu on unikaalse kultuuripärandiga ja modernse elukeskkonnaga, turvaline, säästvalt arenev ja aktiivset koostööd tegev euroopalik linn; atraktiivne ja turvaline reisisiht ning Eesti arengut edendav keskus.', 1,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (4, 'Mitmete leppes esitatud eesmärkide täitmine sõltub Euroopa Liidu, Eesti riigi ja Tartu linna rahalistest võimalustest, mis on otseselt seotud üldise majanduskeskkonna muutustega. Koalitsioonileppe täitmisel tagame linnaeelarve tasakaalu ning eelarvestrateegia järgimise.', 1,19);
-- 6 Ühised väärtused
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (5, 'Võimuliidu moodustamisel ja linnajuhtimisel toetuvad partnerid järgmistele väärtustele:', 6,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (5, 6, 'Avatus – linlaste laialdane kaasamine otsuste tegemisse. Tõdede, uskumuste, väärtuste ja elustiilide paljususe tunnustamine.', 6,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (5, 7, 'Innovatiivsus – uute ideede ja lahenduste väljatöötamine, kasutamine ja tunnustamine.', 6,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (5, 8, 'Säästlikkus – kokkuhoiu ja tõhususe väärtustamine nii valitsemisel, linnaruumi kujundamisel kui ka igapäevases linnaelus.', 6,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (5, 9, 'Sünergia – koostöö ja integreerivate piiriüleste ettevõtmiste soodustamine.', 6,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (5, 10, 'Hoolivus – igale linlasele turvalisuse, enese arendamise võimaluse, laste kasvatamise ja väärikalt vananemise võimaluste tagamine. Iga linnakodanik on kogukonnale väärtuseks.', 6,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (11, 'Peame Tartu üheks suurimaks väärtusteks, linna omanäolisuse kujundajaks ning konkurentsieeliseks erinevate ülikoolide tegevust Tartus.', 6,19);
-- 7 Kultuurilinn
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 'Tartu kultuurielu vajab mitmekesistamist. Eesmärk on saavutada olukord, kus võimalikult paljud eri vanuses ja eri huvidega inimesed leiaksid endale võimaluse tegutseda ja silmaringi avardada. Võtame eesmärgiks, et Tartust saaks 2024. aastal Euroopa kultuuripealinn:', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 13, '1. Viime Tartu UNESCO loovlinnade võrgustikku.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 14, '2. Vaatame üle kultuuriürituste ja -projektide rahastamise põhimõtted ning teeme olukorra parandamiseks vajalikud ümberkorraldused. Muudame väikeprojektide ja -festivalide toetamise aastaringseks. Suurprojektide toetamisel eelistame pikaajalisi lepinguid.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 15, '3. Avame Raadi militaarmaastiku uue kultuurilinnaku tekkeks. Linn teeb vajaliku detailplaneeringu multifunktsionaalse loomelinnaku arendamiseks. ', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 16, '4. Eksponeerime senisest enam kunsti linnale kuuluvates hoonetes ja asutustes.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 17, '5. Toetame professionaalseid kultuuriasutusi.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 18, '6. Parandame koostööd linna-, riigi- ja eramuuseumite vahel.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 19, '7. Suurendame Tartu laululava rolli Tartu kultuurielus ja vaba aja veetmisel.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 20, '8. Otsime võimalusi Tartu I Muusikakooli uutesse ja ajakohastesse ruumidesse viimiseks.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 21, '9. Käivitame Annelinna kultuurikeskuse loomise.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 22, '10. Loome võimalused Tartu kultuuriobjektide ja -ürituste ühisturunduseks.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 23, '11. Jätkame vähemusrahvuste kultuuriseltside toetamist.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 24, '12. Jätkame koostööd teatrietenduste, kontsertide ja näituste korraldajatega soodushindade kehtestamiseks paljulapseliste perede liikmetele, asenduskodude lastele, pensionäridele ning õpetajatele.', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 25, '13. Toetame noorsootöö arenemist professionaalsemaks valdkonnaks, mis toetab süstemaatiliselt noorte eneseleidmist, suhtlemis- ja koostööoskusi ning toimetulekut igapäevaste elu väljakutsetega, sh kaasab noorsootöösse senisest enam töötuid, NEETnoori (mittetöötavad või haridust ega elukutset mitteomandavad noored) jt riskirühma kuuluvaid noori. Selleks tööks kasutatakse enam juba olemasolevat haridus-, kultuuri- ja sporditaristut, sh renoveerides ja kaasajastades olemasolevaid noorsootööasutusi. ', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 26, '14. Tagame igale noorele tartlasele võimaluse osaleda vähemalt ühes huviringis. ', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 27, '15. Anname Tartu suurimale pensionäride ühendusele Kodukotus oma kodu. ', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 28, '16. Toetame konverentsi-, teadus- ja pereturismi ning toidukultuuri arendavaid tegevusi Tartus kui Lõuna-Eesti olulisimas turismisihtkohas. ', 7,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (12, 29, '17. Tagame linna külalistele hästi toimivate infosüsteemide (tänavaviidad, koduleht, nutirakendused, infokeskus) abil mugava viibimise Tartus', 7,19);
-- 8 Mugavad ühendused Tartus ja Tartuga
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 'Tartule kui ettevõtlikule ülikoolilinnale on eluliselt tähtsad kiired ja mugavad ühendused suuremate keskustega. Tartus peab olema sujuv ja loogiliselt toimiv bussi- ja autoliiklus ning võimalus liikuda turvaliselt jalakäijal ja jalgratturil:', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 31, '1. Nelja aasta jooksul renoveerime ja rajame kokku 100 kilomeetri ulatuses jalgratta- ja kõnniteid. Esmajärjekorras ühendame jalgrattateed toimivaks võrgustikuks ning täiendame teede märgistust. ', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 32, '2. 2015. aastaks rajame kõikide Tartu koolide juurde jalgrattaparklad. ', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 33, '3. Otsime võimalusi jalgsi ja rattaga Maarjamõisa meditsiinilinnakust otse üle raudtee kesklinna liikumiseks. ', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 34, '4. Toetame erasektorit uute parkimismajade ja -alade rajamisel, et lahendada parkimisprobleem kesklinnas ja Annelinnas.', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 35, '5. Laiendame jalakäijate ala kesklinnas.', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 36, '6. Ühendame loogiliselt ja mugavalt ajaloolise vanalinna ning uue linnakeskuse Turu tänava ja Emajõe vahel. ', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 37, '7. Käivitame Tartus ühistranspordireformi, mille eesmärgiks on bussiliikluse kvaliteedi edasine parandamine ja liinivõrgu optimeerimine, aga samuti parem keskkonnahoid.  ', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 38, '8. Koostöös Eesti Raudteega pikendame linnasisest raudtee müratõket.', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 39, '9. Koostöös Eesti Raudtee ja ettevõtjatega asume kavandama sadama raudteeharu maaala kasutuselevõttu auto- ja kergliiklusteena. ', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 40, '10. Koostöös riigiga suurendame oluliselt Tartu ja Tallinna vahelist reisirongiliiklust. Kesklinna ja raudteejaama paremaks sidumiseks käivitame jaamaekspressi.', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 41, '11. Toetame Tartu-Riia rongiühenduse käivitamist ning lähirongiliikluse tihendamist Jõgeva, Elva, Valga ja Põlvaga.', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 42, '12. Toetame Tartu Lennujaama turundamist uute liinide avamise eesmärgil.', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 43, '13. Peame oluliseks mitmerealise ja turvalise Tartu-Tallinna maantee ehituse jätkamist.', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 44, '14. Lõunakeskust ja Annelinna ühendava Idaringtee ning Ropka-Ihaste silla ehitamisega vähendame kesklinna tänavate liikluskoormust. ', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 45, '15. Teeme ettevalmistusi Tartu põhjapoolse ümbersõidu ja selle koosseisus oleva silla rajamiseks.', 8,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (30, 46, '16. Jätkame Sõpruse, Võidu ja Kaarsilla renoveerimist.', 8,19);
-- 9 Roheline ja targalt planeeritud linn
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 'Eesmärk on korras ja puhas linnaruum, kus on hea liikuda nii kohalikel elanikel kui ka Tartu külalistel:', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 48, '1. Jätkame Tartu linna piires Emajõe kallasraja korrastamist.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 49, '2. Jätkame koostöös riigi ja erasektoriga väikesadamate, paadisildade, randumiskohtade ja muu jõeliiklustaristu rajamist.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 50, '3. Linlaste puhkevõimaluste avardamiseks ja jõega seotud ettevõtluse ning projektide toetamiseks algatame programmi „Emajõgi elavaks!“.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 51, '4. Koostame Tartu linna parkide, puhkealade ja teiste rohealade teemaplaneeringu.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 52, '5. Rikastame linnaruumi vähemalt 100 uue istepingiga. ', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 53, '6. Jätkame kampaaniat „Istuta oma puu!“.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 54, '7. Rajame igal aastal vähemalt ühe uue avaliku mänguväljaku. ', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 55, '8. Toetame korteriühistuid üldkasutatavate õuealade korrastamisel.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 56, '9. Katame Tartu kesklinna tasuta WiFi võrguga.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 57, '10. Toome linnaruumi sorteerimisvõimalusega prügikastid.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 58, '11. Loome täiendavad taaskasutatavate jäätmete kogumispunktid.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 59, '12. Toetame korteriühistuid maa-aluste prügikonteinerite rajamisel. ', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 60, '13. Tagame, et tartlased sõidavad ka edaspidi keskkonnasäästlike uute bussidega.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 61, '14. Soodustame (keskkonna)säästliku ja kvaliteetse taksoteenuse arendamist.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 62, '15. Kõnniteede paremaks talviseks hoolduseks korraldame riigihanke, mis annab majaomanikele ja korteriühistutele võimaluse mugavalt tellida kõnniteede hooldust. Suurendame linna osalust enimkasutatavate kõnni- ja kergliiklusteede korrashoiul.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 63, '16. Talvisel tänavahooldusel eelistame soolavaba libedustõrjet.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 64, '17. Pimedate linnatänavate valgustamisel võtame kasutusele „targad süsteemid“ ja LED valgustid.', 9,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (47, 65, '18. Toetame rohelise energia arendamist.', 9,19);
-- 10 Sotsiaalne turvatunne
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 'Meie eesmärk on, et kõik Tartu elanikud oleksid sotsiaalselt kaasatud ja kaitstud. Sotsiaalse tõrjutuse ja vaesuse leevendamiseks peab linn lisaks toetuste maksmisele edasi arendama kogukonnateenuseid ning aitama kaasa sotsiaalsete võrgustike kujunemisele:', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 67, '1. Koostöös riigiga suurendame hooldajatoetust ja toetame omastehooldajate koolitust.', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 68, '2. Vähendame omastehooldajate hoolduskoormust võimaldades neil tööelus osaleda.', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 69, '3. Väärtustame vabatahtlike tööd eakate ja puuetega inimeste hooldamisel.', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 70, '4. Tagame üksi elavatele ja erivajadustega inimestele vajadusel kõrvalabi, kodu – või õendushoolduse.', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 71, '5. Erivajadusega inimeste paremaks toimetulekuks tagame invatranspordi ja teiste teenuste parema kättesaadavuse. 6. Viime läbi lastetoetuse reformi, mille tulemusel suureneb lastega perede toimetulek. Muutuste eesmärgiks on suurendada Tartu linna poolt makstavaid lastetoetusi vähemalt 150 000 euro võrra alates 2015. aastast. Alates 2014. aastast makstakse 50eurost koolialguse toetust igale esimesse klassi minevale lapsele. Alates 2015. aastast rakendub koolialguse toetus kogu esimesele kooliastmele (1.−3. klass).', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 72, '6. Käivitame munitsipaalelamuehituse, alustades liikumispuudega isikute vajadustest.', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 73, '7. Loome koostöös riigiga nõustamis- ja tugisüsteemi isikutele, kellel on probleeme oma eluaseme ning elamiskulude haldamisega. ', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 74, '8. Koostöös erasektori ja Töötukassaga korraldame kontaktmesse, mis aitab vähendada tööpuudust linnaelanike, sealhulgas osalise töövõimega ja puudega inimeste seas.', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 75, '9. Jätkame koostööd Tartu Ülikooli Kliinikumiga Maarjamõisa haiglakompleksi välja arendamisel ning meditsiiniteenuste edendamisel. ', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 76, '10. Jätkame tartlaste eest hooldusravi ja hospiitsteenuse omaosaluse tasumist.', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 77, '11. Täiustame matusetoetuse süsteemi.', 10,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (66, 78, '12. Linlaste turvatunde suurendamiseks jätkame Tartu linna kriisiplaani väljaarendamist ning kriisiõppuste korraldamist. ', 10,19);
-- 11 Eesti hariduskeskus
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 'Tartu on väärikas Euroopa ülikoolilinn, mis peab saama parimaks paigaks, kus õppida ja ennast teostada. Kooliuuendust tuleb Tartus jätkata, pöörates järgnevatel aastatel peatähelepanu headele ja ühtlaselt tugevate põhikoolide arendamisele:', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 80, '1. Suurendame Tartu rolli Eesti hariduselus, läheme koolivõrgureformilt üle haridusreformile.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 81, '2. Jätkame Tartu koolide täielikku korrastamist, suunates fookuse põhikoolidele.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 82, '3. Muudame koolitee lastele turvalisemaks.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 83, '4. Loome põhikooliõpilastele võimalused ettevõtlusõppeks.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 84, '5. Suurendame koolides õpi- ja karjäärinõustamist.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 85, '6. Loome eeldused nutilahenduste kasutamiseks koolides, et viia õpetamine ja õppimine Tartus uude ajajärku. ', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 86, '7. Koostöös ülikoolide ning erasektoriga kujundame Tartust hariduslike nutirakenduste arendus- ja kompetentsikeskuse.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 87, '8. Laiendame Miina Härma Gümnaasiumi baasil loodud rahvusvahelise IB-õppe võimalusi siin töötavatele välismaalastele ja tartlastele.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 88, '9. Väärtustame lasteaiaõpetajate tööd samaväärselt kooliõpetajate omaga.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 89, '10. Hoiame Tartu õpetajate palgataset Eesti keskmisest kõrgemal.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 90, '11. Säilitame kooli tugispetsialistide tegevuse rahastamise.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 91, '12. Koostöös erasektoriga jätkame lasteaiakohtade loomist ning lapsehoiuteenuse laiendamist, et kaotada Tartus lasteaiajärjekord', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 92, '13. Kaasajastame lasteaedade mänguväljakud.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 93, '14. Toetame vabaharidust ning Tartu Ülikooli väärikate ülikooli tegevust.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 94, '15. Teeme ülikoolidega koostööd uue moodsa üliõpilasmaja ehitamiseks.', 11,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (79, 95, '16. Väärtustame ning toetame tudengitele ja tudengite poolt korraldatud üritusi.', 11,19);
-- 12 Terve Tartu
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 'Tervise eest hoolitsemine ja spordiga tegelemine on tartlastele oluline. Loome paremad tingimused rahvaspordi ja tervislike eluviiside harrastamiseks. Meie eesmärk on suurendada tartlaste tervelt elatud aastate arvu ning parandada elukvaliteeti:', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 97, '1. Alustame programmiga „Terve Tartu“, et propageerida liikumist ja tervislikku eluviisi.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 98, '2. Teeme ettevalmistusi sotsiaal- ja tervisekeskuste loomiseks linnaosades.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 99, '3. Rahastame jätkuvalt Tartu linna laste visiiditasud Tartu Ülikooli Kliinikumi erakorralise meditsiini osakonnas. Toetame jätkuvalt laste, eakate, noorsportlaste ja Tšernobõli veteranide iga-aastast ennetavat tervisekontrolli. ', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 100, '4. Jätkame ravikindlustamata isikute ambulatoorse ravikulude rahastamist. ', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 101, '5. Tagame igas koolis tervishoiutöötaja olemasolu.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 102, '6. Tõhustame koolides, noortekeskustes jm ennetustööd noorte eemalehoidmiseks sõltuvusainetest.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 103, '7. Toetame noorte terviseteadlikkuse tõstmist "Noorelt-noorele" õppemeetodit rakendades.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 104, '8. Täiendame spordi rahastuse süsteemi.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 105, '9. Noorsportlaste arengu toetamiseks loome koos Eesti Olümpiakomiteega Tartu Spordiakadeemia.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 106, '10. Koostöös erasektoriga arendame välja Sepa jalgpallikompleksi ja renoveerime Annemõisa staadioni.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 107, '11. Ehitame katkematu terviseraja Kvissentalist Ihasteni. ', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 108, '12. Terviseradade ja parkide juurde paigaldame välitrenažöörid koos treenimisjuhistega. Toetame multifunktsionaalsete rahvaspordiplatside rajamist.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 109, '13. Otsime koostöös erasektoriga võimalusi ekstreemspordipargi ja sisehalli rajamiseks.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 110, '14. Otsime võimalusi jäähalli ja liivaväljakuga rannahalli rajamiseks Tartusse.', 12,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (96, 111, '15. Koostöös erasektoriga ehitame Tähtvere spordiparki ja Anne kanali äärde uued pesemis- ja riietumisvõimalustega abihooned.', 12,19);
-- 13 Kodanike linn
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 'Tartus on avatud linnajuhtimine, linnavõim hoolib kõigist linnaelanikest ja peab nendega dialoogi. Töötame välja laiapõhjalise kaasava linnajuhtimise tegevuskava aastani 2020, milles lepitakse kokku meetmed kodanike kaasamiseks ja linnavõimu avatumaks muutmiseks. Esimesed konsensuslikud muudatused linna juhtimises saab ära teha kohe. Need on:', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 113, '1. Jätkame kaasava eelarve printsiibi rakendamist.', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 114, '2. Teavitame jätkuvalt linlasi linnaelu olulistest probleemidest ajakirjanduse vahendusel ning vajadusel käivitame laiaulatusliku diskussiooni.', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 115, '3. Kaasame linnaosade oluliste probleemide lahendamisel vastavate piirkondade elanikud, linnaosaseltsid ja huvirühmade esindajad.  ', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 116, '4. Suurendame volikogu rolli linna juhtimises. Kaasava linnajuhtimise tegevuskava väljatöötamiseks moodustame linnavolikogu komisjoni.', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 117, '5. Volikogu komisjonide juhtimisse kaasatakse opositsiooni liikmeid.', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 118, '6. Planeeringute avalikud väljapanekud kujundatakse sisukateks aruteludeks osapoolte vahel. Tagame kõigile üheselt mõistetava asjaajamise planeerimisel ja ehituslubade väljastamisel. ', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 119, '7. Muudame linnavalitsusega suhtlemise mugavamaks. Loome uusi e- ja nutitelefonilahendusi, kuid tagame igale ea- ja sotsiaalsele rühmale jõukohase linnaga suhtlemise viisi.', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 120, '8. Usaldame ja toetame kodanikeühendusi senisest enam linnaelanikele vajalike hariduse, kultuuri, spordi, vaba aja veetmise, noorsootöö, sotsiaalsfääri ja teiste valdkondade teenuste väljaarendamisel.', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 121, '9. Loome tagasisidesüsteemi linna poolt pakutavate teenuste kvaliteedi hindamiseks.', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 122, '10. Kaasajastame volikogu infosüsteemi, tagame eelnõudega tutvumise võimaluse igas nende kujunemise faasis ja võimaluse jälgida volikogu saadikute otsuseid hääletamisel, et valijal oleks ülevaade oma esindaja otsustest ning seisukohtadest.', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 123, '11. Asjaajamise lihtsustamiseks linnakodanike jaoks juurutame „ühe akna teeninduse“ põhimõtte.', 13,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (112, 124, '12. Noorte ja eakate hääle väärtustamiseks toetame Tartu Noortevolikogu ja Eakate Nõukoja tegevust.', 13,19);
-- 14 Vaba ettevõtluskeskkond
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (125, 'Tartul on head eeldused ettevõtluse edasiseks arendamiseks tänu kõrgkoolide ja piisava hulga haritud tööjõu olemasolule. Selle saavutamise eelduseks on elav dialoog ettevõtjate, ülikoolide ja koolidega:', 14,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (125, 126, '1. Toetame linna juhtides vaba ettevõtluskeskkonda.', 14,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (125, 127, '2. Asjaajamine linnaga olgu võimalikult paberivaba ja kiire.', 14,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (125, 128, '3. Teeme dokumentide menetlusprotsessi kõikidele osapooltele internetis jälgitavaks.', 14,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (125, 129, '4. Ettevõtlust puudutavate otsuste vastuvõtmisel kaasame proaktiivselt vastava valdkonna ettevõtjaid.', 14,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (125, 130, '5. Algatame „Vaimu foorumi“ – linnavalitsuse, ülikoolide ja ettevõtete juhtide regulaarsed kohtumised.', 14,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (125, 131, '6. Viime mentorlusprogrammide raames kokku kogenud ja alustavad ettevõtjad. Soodustame erinevate ärisektorite kogemuste vahetamist ja koostöö tekkimist.', 14,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (125, 132, '7. Loome fondi edukate noorte ettevõtete tunnustamiseks ja toetame alustavate ettevõtjate häid ideid.', 14,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (125, 133, '8. Toetame kutseõppe ja töökoha sidumist.', 14,19);
-- 15 Tartu koostöövõrgustikes ja linna ruumiline areng
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (133, 134, '1. Teeme koostööd Vabariigi Valitsusega, et Tartu roll Eesti suuruselt teise linna ja Lõuna-Eesti keskusena tugevneks.', 15,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (133, 135, '2. Arendame rahvusvahelist koostööd, sh Tartu sõpruslinnadega ja Euroopa Linnade Liidu partneritega, seades eesmärgiks Tartu kõrgharidusmaastiku ja ettevõtluskeskkonna laiema tutvustamise.', 15,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (133, 136, '3. Tihendame koostööd naabervaldadega ning kaitseme Tartu huve maakonnaplaneeringu raames piirkonna asustuse, sotsiaalse taristu ja transpordi planeerimisel. Väldime teenuste dubleerimist.', 15,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (133, 137, '4. Seisame selle eest, et Tartu kesklinn oleks atraktiivse avaliku ruumiga ülikoolilinna süda. Seome teised tekkinud keskused (Lõunakeskus, ERMi piirkond, kõrgkoolide linnakud, raudteejaam) kesklinnaga. Kasutame Emajõge paremini linnaruumi omanäolisemaks muutmiseks.', 15,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (133, 138, '5. Hoiame ära liikumisvajaduse kasvu linnas, planeerides linna “lühikeste teede linna” printsiibist lähtuvalt, et kodu lähedal oleks olemas vajalikud teenused ja esmased vaba aja veetmise võimalused.', 15,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (133, 139, '6. Soosime erinevaid liikumisvõimalusi (jalgsi käimine, rattasõit, ühistransport) selleks, et kogu linnaliiklus oleks sujuv ja sõbralik iga transpordiliigi kasutajale.', 15,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (133, 140, '7. Korraldame erinevate transpordiliikide logistika Tartus, soosides nii mugavat liiklemist linnasiseselt kui sidudes linna paremini ümbritseva regiooni, teiste Eesti keskuste ja maailmaga.', 15,19);
INSERT INTO lubadus(ylemlubadusid,lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (133, 141, '8. Seisame selle eest, et säiliks Tartule omanäoliste linnaosade ja miljööalade nägu ning need kujuneksid hinnatud elukeskkonnaks, tasakaalustades nii valglinnastumise survet.', 15,19);
-- 16 Linnavalitsus
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (142, 'Eesti Reformierakond täidab loodavas linnavalitsuses linnapea ja kahe abilinnapea kohad.', 16,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (143, 'Eesti Keskerakond täidab loodavas linnavalitsuses ühe abilinnapea koha.', 16,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (144, 'Sotsiaaldemokraatlik Erakond täidab loodavas linnavalitsuses kahe abilinnapea kohad.', 16,19);
-- 17 Linnavolikogu
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (145, 'Eesti Reformerakond täidab Tartu Linnavolikogus volikogu aseesimehe ja kolme volikogu komisjoni esimehe kohad.', 17,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (146, 'Eesti Keskerakond täidab Tartu Linnavolikogus volikogu esimehe ja kahe volikogu komisjoni esimehe kohad.', 17,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (147, 'Sotsiaaldemokraatlik Erakond täidab Tartu Linnavolikogus kahe volikogu komisjoni esimehe kohad.', 17,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (148, 'Tartus, 31. oktoobril 2013. a', 17,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (149, 'Urmas Kruuse', 17,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (150, 'Eesti Reformierakond', 17,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (151, 'Aadu Must', 17,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (152, 'Eesti Keskerakond', 17,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (153, 'Heljo Pikhof', 17,19);
INSERT INTO lubadus(lubadusid,mustpealkiri,valdkondid,koalitsioonid) VALUES (154, 'Sotsiaaldemokraatlik Erakond', 17,19);
